title: My First Github Blog
author: SarahtheLlama
email: sarahhardesty94@gmail.com  
description: > # this means to ignore newlines until "baseurl:"
  Budding web developer/IT Support Specialist in the making.
theme: minima
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
